The ``101-lazy_matrix_mul`` module
=============================

Using ``lazy_matrix_mul``
----------------------

Import ``lazy_matrix_mul`` from the ``101-lazy_matrix_mul`` module:

	>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul

Test with a invalid m_a:

	>>> lazy_matrix_mul(None, [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul("String", [[1]]) # doctest: +ELLIPSIS +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([1, 3, 5], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul(["1", "3", 5], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1], [3], 5], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[]], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([["4"]], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[2, "4"]], [[1], [1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1.0], [4.4, "5"]], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1, 4.3], [3]], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

Test with a invalid m_b:

	>>> lazy_matrix_mul([[1]], None) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], "String") # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1]], [1, 3, 5]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], ["1", "3", 5]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1]], [[1], [3], 5]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], []) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], [[]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], [["4"]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1]], [[2, "4"]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	_UFuncNoLoopError: ...

	>>> lazy_matrix_mul([[1]], [[1.0], [4.4, "5"]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1]], [[1, 4.3], [3]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

Test for incompatible sizes of m_a and m_b:

	>>> lazy_matrix_mul([[1]], [[1], [1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

	>>> lazy_matrix_mul([[1, 3]], [[1]]) # doctest: +IGNORE_EXCEPTION_DETAIL
	Traceback (most recent call last):
	  ...
	ValueError: ...

Test for correct multiplications:

	>>> lazy_matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
	[[7, 10], [15, 22]]

	>>> lazy_matrix_mul([[1, 1]], [[1], [1]])
	[[2]]

	>>> lazy_matrix_mul([[1, 2]], [[3, 4], [5, 6]])
	[[13, 16]]
